2015/08/17 02:16:47 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\php\yii\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\php\yii\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\xampp\php\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\php\yii\framework\base\CModule.php(523): CModule->getComponent('bootstrap')
#3 C:\xampp\php\yii\framework\base\CApplication.php(163): CModule->preloadComponents()
#4 C:\xampp\php\yii\framework\YiiBase.php(125): CApplication->__construct('C:\\xampp\\htdocs...')
#5 C:\xampp\php\yii\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\avaliacao360\app\index.php(13): YiiBase::createWebApplication('C:\\xampp\\htdocs...')
#7 {main}
REQUEST_URI=/avaliacao360/app/index.php
---
2015/08/17 02:20:39 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\php\yii\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\php\yii\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\xampp\php\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\php\yii\framework\base\CModule.php(523): CModule->getComponent('bootstrap')
#3 C:\xampp\php\yii\framework\base\CApplication.php(163): CModule->preloadComponents()
#4 C:\xampp\php\yii\framework\YiiBase.php(125): CApplication->__construct('C:\\xampp\\htdocs...')
#5 C:\xampp\php\yii\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\avaliacao360\app\index.php(13): YiiBase::createWebApplication('C:\\xampp\\htdocs...')
#7 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php
---
2015/08/17 02:20:43 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\php\yii\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\php\yii\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\xampp\php\yii\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#2 C:\xampp\php\yii\framework\base\CModule.php(523): CModule->getComponent('bootstrap')
#3 C:\xampp\php\yii\framework\base\CApplication.php(163): CModule->preloadComponents()
#4 C:\xampp\php\yii\framework\YiiBase.php(125): CApplication->__construct('C:\\xampp\\htdocs...')
#5 C:\xampp\php\yii\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\avaliacao360\app\index.php(13): YiiBase::createWebApplication('C:\\xampp\\htdocs...')
#7 {main}
REQUEST_URI=/avaliacao360/app/
---
2015/08/17 12:58:34 [error] [exception.CException] exception 'CException' with message 'A propriedade "CHttpRequest.basePath" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\views\site\login.php(11): CComponent->__get('basePath')
#1 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#2 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#5 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(89): CController->render('login', Array)
#6 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=
---
2015/08/18 01:54:53 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.textField" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2529): CComponent->__get('textField')
#1 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(LoginForm), 'textField')
#2 C:\xampp\php\yii\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(LoginForm), 'textField', Array)
#3 C:\xampp\php\yii\framework\web\widgets\CActiveForm.php(725): CHtml::activeTextField(Object(LoginForm), 'textField', Array)
#4 [internal function]: CActiveForm->textField(Object(LoginForm), 'textField', Array)
#5 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1293): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1152): TbActiveForm->verticalGroup(Array, Object(LoginForm), 'textField', Array)
#7 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(389): TbActiveForm->customFieldGroupInternal(Array, Object(LoginForm), 'textField', Array)
#8 C:\xampp\htdocs\avaliacao360\app\protected\views\site\login.php(40): TbActiveForm->textFieldGroup(Object(LoginForm), 'textField')
#9 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#10 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#11 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(89): CController->render('login', Array)
#14 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#15 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#19 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#20 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/
---
2015/08/20 13:59:00 [error] [php] include(Funcionario.php): failed to open stream: No such file or directory (C:\xampp\php\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\components\UserIdentity.php(19): spl_autoload_call()
#1 C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php(49): UserIdentity->authenticate()
#2 C:\xampp\php\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\php\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 C:\xampp\php\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(85): LoginForm->validate()
#6 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\php\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\php\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
in C:\xampp\htdocs\avaliacao360\app\protected\components\UserIdentity.php (19)
in C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php (49)
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (85)
2015/08/20 14:00:47 [error] [exception.CException] exception 'CException' with message 'A propriedade "UserIdentity.email" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\components\UserIdentity.php(21): CComponent->__get('email')
#1 C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php(49): UserIdentity->authenticate()
#2 C:\xampp\php\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\php\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\php\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(85): CModel->validate()
#6 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:07:22 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:07:22 [warning] [application] Failed to set unsafe attribute "password" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:07:22 [warning] [application] Failed to set unsafe attribute "rememberMe" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:07:22 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.username" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2529): CComponent->__get('username')
#1 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(LoginForm), 'username')
#2 C:\xampp\php\yii\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(LoginForm), 'username', Array)
#3 C:\xampp\php\yii\framework\web\widgets\CActiveForm.php(725): CHtml::activeTextField(Object(LoginForm), 'username', Array)
#4 [internal function]: CActiveForm->textField(Object(LoginForm), 'username', Array)
#5 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1293): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1152): TbActiveForm->verticalGroup(Array, Object(LoginForm), 'username', Array)
#7 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(389): TbActiveForm->customFieldGroupInternal(Array, Object(LoginForm), 'username', Array)
#8 C:\xampp\htdocs\avaliacao360\app\protected\views\site\login.php(29): TbActiveForm->textFieldGroup(Object(LoginForm), 'username')
#9 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#10 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#11 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(89): CController->render('login', Array)
#14 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#15 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#19 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#20 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:08:52 [warning] [application] Failed to set unsafe attribute "username" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:08:52 [warning] [application] Failed to set unsafe attribute "password" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:08:52 [warning] [application] Failed to set unsafe attribute "rememberMe" of "LoginForm".
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php (83)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/20 14:19:19 [error] [exception.CException] exception 'CException' with message 'A propriedade "UserIdentity._id" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\components\UserIdentity.php(30): CComponent->__set('_id', '1')
#1 C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php(46): UserIdentity->authenticate()
#2 C:\xampp\php\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('senha', Array)
#3 C:\xampp\php\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'senha')
#4 C:\xampp\php\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(85): CModel->validate()
#6 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:20:06 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.rememberMe" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\models\LoginForm.php(61): CComponent->__get('rememberMe')
#1 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(85): LoginForm->login()
#2 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#3 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#8 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:20:47 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Sua requisição é inválida.' in C:\xampp\php\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('funcionario/upd...')
#10 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=funcionario/update
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/20 14:21:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Você não está autorizado a realizar essa operação.' in C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Voc\xC3\xAA n\xC3\xA3o est\xC3...')
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('funcionario/adm...')
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=funcionario/admin
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=funcionario/index
---
2015/08/20 14:39:52 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Sua requisição é inválida.' in C:\xampp\php\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('funcionario/upd...')
#10 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=funcionario/update
---
2015/08/20 14:42:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin
---
2015/08/20 14:44:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/default".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/default')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/default
---
2015/08/22 14:32:45 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Sua requisição é inválida.' in C:\xampp\php\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('funcionario/upd...')
#10 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=funcionario/update
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/22 16:00:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin
---
2015/08/22 16:49:23 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Sua requisição é inválida.' in C:\xampp\php\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#10 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/update
---
2015/08/22 16:53:08 [error] [exception.CException] exception 'CException' with message 'A propriedade "AdminModule.theme" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\php\yii\framework\base\CModule.php(513): CComponent->__set('theme', 'sb-admin')
#1 C:\xampp\php\yii\framework\base\CModule.php(86): CModule->configure(Array)
#2 C:\xampp\php\yii\framework\YiiBase.php(206): CModule->__construct('admin', NULL, Array)
#3 C:\xampp\php\yii\framework\base\CModule.php(282): YiiBase::createComponent('admin.AdminModu...', 'admin', NULL, Array)
#4 C:\xampp\php\yii\framework\web\CWebApplication.php(337): CModule->getModule('admin')
#5 C:\xampp\php\yii\framework\web\CWebApplication.php(276): CWebApplication->createController('admin/funcionar...')
#6 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#7 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/22 16:57:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "funcionario".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('funcionario')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=funcionario
---
2015/08/22 16:57:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "funcionario/index".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('funcionario/ind...')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=funcionario/index
---
2015/08/22 16:57:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 16:57:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:18:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:18:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:19:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:19:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:19:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:20:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:22:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:25:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:27:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:27:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:28:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:54:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:54:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:54:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:55:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:55:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:55:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 17:56:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/create')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/create
---
2015/08/22 19:29:08 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Você não está autorizado a realizar essa operação.' in C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Voc\xC3\xAA n\xC3\xA3o est\xC3...')
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/questiona...')
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/questionario/admin
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/questionario
---
2015/08/22 19:37:32 [error] [exception.CException] exception 'CException' with message 'A propriedade "CWebUser.username" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CWebUser.php(146): CComponent->__get('username')
#1 C:\xampp\htdocs\avaliacao360\app\themes\sb-admin\views\layouts\main.php(61): CWebUser->__get('username')
#2 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div class="spa...')
#6 C:\xampp\php\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div class="spa...')
#7 C:\xampp\php\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\php\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\avaliacao360\app\protected\views\layouts\column2.php(22): CBaseController->endContent()
#10 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\QuestionarioController.php(122): CController->render('index', Array)
#14 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): QuestionarioController->actionIndex()
#15 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#17 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#18 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#19 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#20 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#21 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#22 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#23 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('')
#24 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/questiona...')
#25 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#26 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#27 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/questionario
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/questionario
---
2015/08/22 19:38:11 [error] [php] Object of class CWebUser could not be converted to string (C:\xampp\htdocs\avaliacao360\app\themes\sb-admin\views\layouts\main.php:61)
Stack trace:
#0 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(76): QuestionarioController->renderFile()
#1 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#2 C:\xampp\php\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#3 C:\xampp\php\yii\framework\web\CBaseController.php(206): CContentDecorator->run()
#4 C:\xampp\php\yii\framework\web\CBaseController.php(300): QuestionarioController->endWidget()
#5 C:\xampp\htdocs\avaliacao360\app\protected\views\layouts\column2.php(22): QuestionarioController->endContent()
#6 C:\xampp\php\yii\framework\web\CBaseController.php(126): require()
#7 C:\xampp\php\yii\framework\web\CBaseController.php(95): QuestionarioController->renderInternal()
#8 C:\xampp\php\yii\framework\web\CController.php(784): QuestionarioController->renderFile()
#9 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\QuestionarioController.php(122): QuestionarioController->render()
#10 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): QuestionarioController->actionIndex()
#11 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): QuestionarioController->runAction()
#13 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#14 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#15 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): QuestionarioController->filterAccessControl()
#16 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#17 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#18 C:\xampp\php\yii\framework\web\CController.php(265): QuestionarioController->runActionWithFilters()
#19 C:\xampp\php\yii\framework\web\CWebApplication.php(282): QuestionarioController->run()
#20 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#21 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#22 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/questionario
in C:\xampp\htdocs\avaliacao360\app\themes\sb-admin\views\layouts\main.php (61)
in C:\xampp\htdocs\avaliacao360\app\protected\views\layouts\column2.php (22)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\QuestionarioController.php (122)
2015/08/22 19:52:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin/empresa/create".' in C:\xampp\php\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/empresa/c...')
#1 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/empresa/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php
---
2015/08/22 19:57:47 [error] [exception.CException] exception 'CException' with message 'A propriedade "Empresa.logradouro" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('logradouro')
#1 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('logradouro')
#2 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Empresa), 'logradouro')
#3 C:\xampp\php\yii\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Empresa), 'logradouro', Array)
#4 C:\xampp\php\yii\framework\web\widgets\CActiveForm.php(725): CHtml::activeTextField(Object(Empresa), 'logradouro', Array)
#5 [internal function]: CActiveForm->textField(Object(Empresa), 'logradouro', Array)
#6 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1293): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1152): TbActiveForm->verticalGroup(Array, Object(Empresa), 'logradouro', Array)
#8 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(389): TbActiveForm->customFieldGroupInternal(Array, Object(Empresa), 'logradouro', Array)
#9 C:\xampp\htdocs\avaliacao360\app\protected\views\endereco\_form.php(10): TbActiveForm->textFieldGroup(Object(Empresa), 'logradouro', Array)
#10 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\create.php(16): CController->renderPartial('../endereco/_fo...', Array)
#14 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#15 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#16 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#17 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#18 C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php(73): CController->render('create', Array)
#19 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): EmpresaController->actionCreate()
#20 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#21 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#22 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#23 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#24 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#25 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#26 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#27 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#28 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#29 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('empresa/create')
#30 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#31 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#32 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=empresa/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php
---
2015/08/22 20:01:41 [error] [php] Undefined variable: model (C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\_form.php:10)
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(869): EmpresaController->renderFile()
#1 C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\create.php(15): EmpresaController->renderPartial()
#2 C:\xampp\php\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\php\yii\framework\web\CBaseController.php(95): EmpresaController->renderInternal()
#4 C:\xampp\php\yii\framework\web\CController.php(869): EmpresaController->renderFile()
#5 C:\xampp\php\yii\framework\web\CController.php(782): EmpresaController->renderPartial()
#6 C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php(75): EmpresaController->render()
#7 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): EmpresaController->actionCreate()
#8 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): EmpresaController->runAction()
#10 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#12 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): EmpresaController->filterAccessControl()
#13 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#14 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\php\yii\framework\web\CController.php(265): EmpresaController->runActionWithFilters()
#16 C:\xampp\php\yii\framework\web\CWebApplication.php(282): EmpresaController->run()
#17 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#18 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=empresa/create
in C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\_form.php (10)
in C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\create.php (15)
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php (75)
2015/08/22 20:02:42 [error] [php] Undefined variable: modelEndereco (C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\_form.php:10)
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(869): EmpresaController->renderFile()
#1 C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\create.php(15): EmpresaController->renderPartial()
#2 C:\xampp\php\yii\framework\web\CBaseController.php(126): require()
#3 C:\xampp\php\yii\framework\web\CBaseController.php(95): EmpresaController->renderInternal()
#4 C:\xampp\php\yii\framework\web\CController.php(869): EmpresaController->renderFile()
#5 C:\xampp\php\yii\framework\web\CController.php(782): EmpresaController->renderPartial()
#6 C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php(75): EmpresaController->render()
#7 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): EmpresaController->actionCreate()
#8 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): EmpresaController->runAction()
#10 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#11 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#12 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): EmpresaController->filterAccessControl()
#13 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#14 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#15 C:\xampp\php\yii\framework\web\CController.php(265): EmpresaController->runActionWithFilters()
#16 C:\xampp\php\yii\framework\web\CWebApplication.php(282): EmpresaController->run()
#17 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#18 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=empresa/create
in C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\_form.php (10)
in C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\create.php (15)
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php (75)
2015/08/22 20:06:06 [error] [php] Undefined variable: modelEmpresa (C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\create.php:15)
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(869): EmpresaController->renderFile()
#1 C:\xampp\php\yii\framework\web\CController.php(782): EmpresaController->renderPartial()
#2 C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php(73): EmpresaController->render()
#3 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): EmpresaController->actionCreate()
#4 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): EmpresaController->runAction()
#6 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#8 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): EmpresaController->filterAccessControl()
#9 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#10 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\php\yii\framework\web\CController.php(265): EmpresaController->runActionWithFilters()
#12 C:\xampp\php\yii\framework\web\CWebApplication.php(282): EmpresaController->run()
#13 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#14 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=empresa/create
in C:\xampp\htdocs\avaliacao360\app\protected\views\empresa\create.php (15)
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 20:09:40 [error] [php] urlencode() expects parameter 1 to be string, object given (C:\xampp\php\yii\framework\web\CUrlManager.php:440)
Stack trace:
#0 C:\xampp\php\yii\framework\web\CUrlManager.php(310): CUrlManager->createUrlDefault()
#1 C:\xampp\php\yii\framework\base\CApplication.php(543): CUrlManager->createUrl()
#2 C:\xampp\php\yii\framework\web\CController.php(967): CWebApplication->createUrl()
#3 C:\xampp\php\yii\framework\web\CController.php(1028): EmpresaController->createUrl()
#4 C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php(68): EmpresaController->redirect()
#5 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): EmpresaController->actionCreate()
#6 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): EmpresaController->runAction()
#8 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#10 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): EmpresaController->filterAccessControl()
#11 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#13 C:\xampp\php\yii\framework\web\CController.php(265): EmpresaController->runActionWithFilters()
#14 C:\xampp\php\yii\framework\web\CWebApplication.php(282): EmpresaController->run()
#15 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=empresa/create
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php (68)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 20:17:06 [error] [php] A session had already been started - ignoring session_start() (C:\xampp\htdocs\avaliacao360\app\themes\front\views\layouts\main.php:1)
Stack trace:
#0 C:\xampp\php\yii\framework\web\CBaseController.php(95): EmpresaController->renderInternal()
#1 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(76): EmpresaController->renderFile()
#2 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#3 C:\xampp\php\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#4 C:\xampp\php\yii\framework\web\CBaseController.php(206): CContentDecorator->run()
#5 C:\xampp\php\yii\framework\web\CBaseController.php(300): EmpresaController->endWidget()
#6 C:\xampp\htdocs\avaliacao360\app\themes\front\views\layouts\column1.php(6): EmpresaController->endContent()
#7 C:\xampp\php\yii\framework\web\CBaseController.php(126): require()
#8 C:\xampp\php\yii\framework\web\CBaseController.php(95): EmpresaController->renderInternal()
#9 C:\xampp\php\yii\framework\web\CController.php(784): EmpresaController->renderFile()
#10 C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php(75): EmpresaController->render()
#11 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): EmpresaController->actionCreate()
#12 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): EmpresaController->runAction()
#14 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#16 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): EmpresaController->filterAccessControl()
#17 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#18 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\php\yii\framework\web\CController.php(265): EmpresaController->runActionWithFilters()
#20 C:\xampp\php\yii\framework\web\CWebApplication.php(282): EmpresaController->run()
#21 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#22 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=empresa/create
in C:\xampp\htdocs\avaliacao360\app\themes\front\views\layouts\main.php (1)
in C:\xampp\htdocs\avaliacao360\app\themes\front\views\layouts\column1.php (6)
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php (75)
2015/08/22 20:17:26 [error] [php] A session had already been started - ignoring session_start() (C:\xampp\htdocs\avaliacao360\app\themes\front\views\layouts\main.php:1)
Stack trace:
#0 C:\xampp\php\yii\framework\web\CBaseController.php(95): EmpresaController->renderInternal()
#1 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(76): EmpresaController->renderFile()
#2 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#3 C:\xampp\php\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#4 C:\xampp\php\yii\framework\web\CBaseController.php(206): CContentDecorator->run()
#5 C:\xampp\php\yii\framework\web\CBaseController.php(300): EmpresaController->endWidget()
#6 C:\xampp\htdocs\avaliacao360\app\themes\front\views\layouts\column1.php(6): EmpresaController->endContent()
#7 C:\xampp\php\yii\framework\web\CBaseController.php(126): require()
#8 C:\xampp\php\yii\framework\web\CBaseController.php(95): EmpresaController->renderInternal()
#9 C:\xampp\php\yii\framework\web\CController.php(784): EmpresaController->renderFile()
#10 C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php(75): EmpresaController->render()
#11 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): EmpresaController->actionCreate()
#12 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): EmpresaController->runAction()
#14 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#16 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): EmpresaController->filterAccessControl()
#17 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#18 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\php\yii\framework\web\CController.php(265): EmpresaController->runActionWithFilters()
#20 C:\xampp\php\yii\framework\web\CWebApplication.php(282): EmpresaController->run()
#21 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#22 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=empresa/create
in C:\xampp\htdocs\avaliacao360\app\themes\front\views\layouts\main.php (1)
in C:\xampp\htdocs\avaliacao360\app\themes\front\views\layouts\column1.php (6)
in C:\xampp\htdocs\avaliacao360\app\protected\controllers\EmpresaController.php (75)
2015/08/22 20:53:42 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Você não está autorizado a realizar essa operação.' in C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Voc\xC3\xAA n\xC3\xA3o est\xC3...')
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('endereco/admin')
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=endereco/admin
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/22 21:09:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Você não está autorizado a realizar essa operação.' in C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Voc\xC3\xAA n\xC3\xA3o est\xC3...')
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/questiona...')
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/questionario/admin
HTTP_REFERER=http://192.168.0.105/avaliacao360/app/index.php?r=admin/questionario/create
---
2015/08/22 22:14:57 [error] [exception.CException] exception 'CException' with message 'TbActiveForm and its behaviors do not have a method or closure named "passwordFielGroup".' in C:\xampp\php\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\views\funcionario\_form.php(16): CComponent->__call('passwordFielGro...', Array)
#1 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\views\funcionario\_form.php(16): TbActiveForm->passwordFielGroup(Object(Funcionario), 'senha', Array)
#2 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\views\funcionario\create.php(15): CController->renderPartial('_form', Array)
#6 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#10 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(76): CController->render('create', Array)
#11 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#12 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#21 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#22 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/22 22:15:58 [error] [exception.CException] exception 'CException' with message 'A propriedade "Funcionario.repetirSenha" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('repetirSenha')
#1 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('repetirSenha')
#2 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Funcionario), 'repetirSenha')
#3 C:\xampp\php\yii\framework\web\helpers\CHtml.php(1628): CHtml::activeInputField('password', Object(Funcionario), 'repetirSenha', Array)
#4 C:\xampp\php\yii\framework\web\widgets\CActiveForm.php(771): CHtml::activePasswordField(Object(Funcionario), 'repetirSenha', Array)
#5 [internal function]: CActiveForm->passwordField(Object(Funcionario), 'repetirSenha', Array)
#6 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1293): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1152): TbActiveForm->verticalGroup(Array, Object(Funcionario), 'repetirSenha', Array)
#8 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(440): TbActiveForm->customFieldGroupInternal(Array, Object(Funcionario), 'repetirSenha', Array)
#9 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\views\funcionario\_form.php(30): TbActiveForm->passwordFieldGroup(Object(Funcionario), 'repetirSenha', Array)
#10 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\views\funcionario\create.php(15): CController->renderPartial('_form', Array)
#14 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#15 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#16 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#17 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#18 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(76): CController->render('create', Array)
#19 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#20 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#21 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#22 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#23 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#24 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#25 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#26 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#27 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#28 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#29 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#30 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#31 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#32 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/22 22:16:35 [error] [exception.CException] exception 'CException' with message 'A propriedade "Funcionario.repetirSenha" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('repetirSenha')
#1 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('repetirSenha')
#2 C:\xampp\php\yii\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Funcionario), 'repetirSenha')
#3 C:\xampp\php\yii\framework\web\helpers\CHtml.php(1628): CHtml::activeInputField('password', Object(Funcionario), 'repetirSenha', Array)
#4 C:\xampp\php\yii\framework\web\widgets\CActiveForm.php(771): CHtml::activePasswordField(Object(Funcionario), 'repetirSenha', Array)
#5 [internal function]: CActiveForm->passwordField(Object(Funcionario), 'repetirSenha', Array)
#6 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1293): call_user_func_array(Array, Array)
#7 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(1152): TbActiveForm->verticalGroup(Array, Object(Funcionario), 'repetirSenha', Array)
#8 C:\xampp\htdocs\avaliacao360\app\protected\extensions\yiibooster\widgets\TbActiveForm.php(440): TbActiveForm->customFieldGroupInternal(Array, Object(Funcionario), 'repetirSenha', Array)
#9 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\views\funcionario\_form.php(30): TbActiveForm->passwordFieldGroup(Object(Funcionario), 'repetirSenha', Array)
#10 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\views\funcionario\create.php(15): CController->renderPartial('_form', Array)
#14 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#15 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#16 C:\xampp\php\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#17 C:\xampp\php\yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#18 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(79): CController->render('create', Array)
#19 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#20 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#21 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#22 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#23 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#24 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#25 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#26 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#27 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#28 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#29 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#30 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#31 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#32 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/22 22:58:59 [error] [php] include(Funcoes.php): failed to open stream: No such file or directory (C:\xampp\php\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(18): spl_autoload_call()
#1 C:\xampp\php\yii\framework\web\CWebApplication.php(281): FuncionarioController->init()
#2 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (18)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 22:59:38 [error] [php] require_once(Funcoes.php): failed to open stream: No such file or directory (C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php:8)
Stack trace:
#0 C:\xampp\php\yii\framework\web\CWebApplication.php(338): CWebApplication->createController()
#1 C:\xampp\php\yii\framework\web\CWebApplication.php(276): CWebApplication->createController()
#2 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#3 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (8)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (8)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 22:59:56 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 23:00:03 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 23:09:26 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 23:09:53 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 23:09:53 [error] [php] Undefined index: funcLogado (C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php:79)
Stack trace:
#0 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (79)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 23:10:17 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Você não está autorizado a realizar essa operação.' in C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Voc\xC3\xAA n\xC3\xA3o est\xC3...')
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('endereco/admin')
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=endereco/admin
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/22 23:10:50 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 23:10:50 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.empresa_id" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(80): CComponent->__get('empresa_id')
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/22 23:12:31 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/22 23:12:31 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.empresa_id" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(80): CComponent->__get('empresa_id')
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/24 12:58:59 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 12:58:59 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.empresa_id" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(80): CComponent->__get('empresa_id')
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/24 13:09:13 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:09:13 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.empresa_id" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(80): CComponent->__get('empresa_id')
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/24 13:11:22 [error] [exception.CException] exception 'CException' with message 'LoginForm and its behaviors do not have a method or closure named "getId".' in C:\xampp\php\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(86): CComponent->__call('getId', Array)
#1 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(86): LoginForm->getId()
#2 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#3 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#8 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/24 13:12:46 [error] [exception.CException] exception 'CException' with message 'A propriedade "LoginForm.id" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(86): CComponent->__get('id')
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#6 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#7 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/24 13:17:24 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:22:31 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:24:56 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:25:09 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:26:04 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:26:07 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:26:14 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:29:12 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:30:56 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:31:01 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:31:07 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:31:57 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:34:40 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:35:50 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:35:50 [error] [php] Object of class Funcionario could not be converted to string (C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php:87)
Stack trace:
#0 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (87)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:36:42 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:36:42 [error] [php] Object of class Funcionario could not be converted to string (C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php:87)
Stack trace:
#0 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (87)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:38:09 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:38:27 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:38:39 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:48:53 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:48:57 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:52:30 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:52:37 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:52:40 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 13:52:46 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:13:53 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (78)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:18:26 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:27:47 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:28:00 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:28:19 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:29:59 [error] [php] include(lenght.php): failed to open stream: No such file or directory (C:\xampp\php\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\php\yii\framework\validators\CValidator.php(186): import()
#1 C:\xampp\php\yii\framework\base\CModel.php(287): createValidator()
#2 C:\xampp\php\yii\framework\base\CModel.php(260): Funcionario->createValidators()
#3 C:\xampp\php\yii\framework\base\CModel.php(547): Funcionario->getValidators()
#4 C:\xampp\php\yii\framework\base\CModel.php(468): Funcionario->getSafeAttributeNames()
#5 C:\xampp\php\yii\framework\base\CComponent.php(152): Funcionario->setAttributes()
#6 C:\xampp\php\yii\framework\db\ar\CActiveRecord.php(161): Funcionario->__set()
#7 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(73): Funcionario->__set()
#8 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#9 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#10 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#11 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#13 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#14 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#15 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#17 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#18 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#19 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:30:11 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:30:24 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:30:32 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:35:11 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:36:05 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:36:53 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:37:18 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:39:34 [error] [exception.CException] exception 'CException' with message 'A propriedade "CNumberValidator.toSmall" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\php\yii\framework\validators\CValidator.php(189): CComponent->__set('toSmall', 'Selecione a per...')
#1 C:\xampp\php\yii\framework\base\CModel.php(287): CValidator::createValidator('numerical', Object(Funcionario), 'permissao', Array)
#2 C:\xampp\php\yii\framework\base\CModel.php(260): CModel->createValidators()
#3 C:\xampp\php\yii\framework\base\CModel.php(547): CModel->getValidators()
#4 C:\xampp\php\yii\framework\base\CModel.php(468): CModel->getSafeAttributeNames()
#5 C:\xampp\php\yii\framework\base\CComponent.php(152): CModel->setAttributes(Array)
#6 C:\xampp\php\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('attributes', Array)
#7 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(73): CActiveRecord->__set('attributes', Array)
#8 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#9 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#16 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#18 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#19 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/24 14:39:49 [warning] [application] Failed to set unsafe attribute "departamento" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:43:39 [error] [exception.CException] exception 'CException' with message 'A propriedade "CWebUser.username" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CWebUser.php(146): CComponent->__get('username')
#1 C:\xampp\htdocs\avaliacao360\app\themes\sb-admin\views\layouts\main.php(132): CWebUser->__get('username')
#2 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\php\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\php\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\php\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\avaliacao360\app\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(90): CController->render('create', Array)
#14 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#15 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#17 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#18 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#19 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#20 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#21 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#22 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#23 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#24 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#25 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#26 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#27 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/24 14:44:18 [error] [exception.CException] exception 'CException' with message 'A propriedade "CWebUser.email" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CWebUser.php(146): CComponent->__get('email')
#1 C:\xampp\htdocs\avaliacao360\app\themes\sb-admin\views\layouts\main.php(132): CWebUser->__get('email')
#2 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\php\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\php\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\php\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\avaliacao360\app\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(90): CController->render('create', Array)
#14 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#15 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#17 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#18 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#19 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#20 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#21 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#22 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#23 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#24 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#25 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#26 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#27 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/24 14:44:28 [error] [exception.CException] exception 'CException' with message 'A propriedade "CWebUser.user" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\web\auth\CWebUser.php(146): CComponent->__get('user')
#1 C:\xampp\htdocs\avaliacao360\app\themes\sb-admin\views\layouts\main.php(132): CWebUser->__get('user')
#2 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\php\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\php\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\php\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\php\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\avaliacao360\app\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\php\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\php\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\php\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(90): CController->render('create', Array)
#14 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#15 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#17 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#18 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#19 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#20 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#21 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#22 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#23 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#24 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#25 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#26 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#27 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/24 14:46:19 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php:75)
Stack trace:
#0 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#1 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#4 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#7 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (75)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 14:49:45 [error] [exception.CException] exception 'CException' with message 'A propriedade "UserIdentity._id" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\controllers\SiteController.php(86): CComponent->__get('_id')
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\php\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('login')
#6 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#7 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=site/login
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=site/login
---
2015/08/24 15:00:54 [error] [exception.CException] exception 'CException' with message 'Funcionario tem uma regra de validação inválida. A regra deve especificar atributos para serem validados e o nome do validador.' in C:\xampp\php\yii\framework\base\CModel.php:289
Stack trace:
#0 C:\xampp\php\yii\framework\base\CModel.php(260): CModel->createValidators()
#1 C:\xampp\php\yii\framework\base\CModel.php(547): CModel->getValidators()
#2 C:\xampp\php\yii\framework\base\CModel.php(468): CModel->getSafeAttributeNames()
#3 C:\xampp\php\yii\framework\base\CComponent.php(152): CModel->setAttributes(Array)
#4 C:\xampp\php\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('attributes', Array)
#5 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(73): CActiveRecord->__set('attributes', Array)
#6 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#7 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#16 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#17 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/24 15:01:15 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:01:36 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:03:54 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:04:18 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:04:46 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:06:16 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:06:48 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:07:12 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:07:19 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:07:23 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:08:25 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:08:47 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:11:42 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:12:02 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:12:10 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:12:24 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:19:00 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:19:00 [error] [exception.CException] exception 'CException' with message 'A propriedade "Funcionario.image" não está definida.' in C:\xampp\php\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\php\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('image')
#1 C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php(161): CActiveRecord->__get('image')
#2 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(85): Funcionario->salvaImagem(Object(Funcionario))
#3 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#4 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\php\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\php\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\php\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin/funcionar...')
#14 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\avaliacao360\app\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
HTTP_REFERER=http://localhost/avaliacao360/app/index.php?r=admin/funcionario/create
---
2015/08/24 15:19:16 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:19:36 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:19:36 [error] [php] move_uploaded_file(/avaliacao360/appimages/funcionarios): failed to open stream: No such file or directory (C:\xampp\php\yii\framework\web\CUploadedFile.php:198)
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(85): Funcionario->salvaImagem()
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php (161)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (85)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:19:51 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:19:54 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:20:04 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:20:11 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:20:11 [error] [php] move_uploaded_file(/avaliacao360/app/images/funcionarios): failed to open stream: No such file or directory (C:\xampp\php\yii\framework\web\CUploadedFile.php:198)
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(85): Funcionario->salvaImagem()
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php (161)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (85)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:23:55 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:24:01 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:24:01 [error] [php] move_uploaded_file(/avaliacao360/app/images/funcionarios): failed to open stream: No such file or directory (C:\xampp\php\yii\framework\web\CUploadedFile.php:198)
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(84): Funcionario->salvaImagem()
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php (161)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (84)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:24:19 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:24:28 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:25:10 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:25:10 [error] [php] move_uploaded_file(): The second argument to copy() function cannot be a directory (C:\xampp\php\yii\framework\web\CUploadedFile.php:198)
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(84): Funcionario->salvaImagem()
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php (163)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (84)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:25:59 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:25:59 [error] [php] move_uploaded_file(): The second argument to copy() function cannot be a directory (C:\xampp\php\yii\framework\web\CUploadedFile.php:198)
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(84): Funcionario->salvaImagem()
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php (163)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (84)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:27:25 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:28:27 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:28:27 [error] [php] move_uploaded_file(): The second argument to copy() function cannot be a directory (C:\xampp\php\yii\framework\web\CUploadedFile.php:198)
Stack trace:
#0 C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php(84): Funcionario->salvaImagem()
#1 C:\xampp\php\yii\framework\web\actions\CInlineAction.php(49): FuncionarioController->actionCreate()
#2 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#4 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#7 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#10 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#11 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php (164)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (84)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:31:43 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:32:11 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:33:40 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:33:40 [error] [php] Array to string conversion (C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php:166)
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#2 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#4 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#5 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#6 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#9 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php (166)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (84)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:34:56 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:34:56 [error] [php] Array to string conversion (C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php:166)
Stack trace:
#0 C:\xampp\php\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(133): FuncionarioController->runAction()
#2 C:\xampp\php\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\php\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#4 C:\xampp\php\yii\framework\web\filters\CInlineFilter.php(58): FuncionarioController->filterAccessControl()
#5 C:\xampp\php\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#6 C:\xampp\php\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\php\yii\framework\web\CController.php(265): FuncionarioController->runActionWithFilters()
#8 C:\xampp\php\yii\framework\web\CWebApplication.php(282): FuncionarioController->run()
#9 C:\xampp\php\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 C:\xampp\php\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\avaliacao360\app\index.php(13): CWebApplication->run()
REQUEST_URI=/avaliacao360/app/index.php?r=admin/funcionario/create
in C:\xampp\htdocs\avaliacao360\app\protected\models\Funcionario.php (166)
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (84)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:35:26 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:36:45 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:38:30 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:38:53 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:39:41 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:41:55 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:42:02 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 15:42:34 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:46:39 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:47:10 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:47:54 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:49:34 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:49:43 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:50:31 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:51:12 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:51:58 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:52:01 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:52:06 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:52:12 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
2015/08/24 16:52:18 [warning] [application] Failed to set unsafe attribute "foto" of "Funcionario".
in C:\xampp\htdocs\avaliacao360\app\protected\modules\admin\controllers\FuncionarioController.php (73)
in C:\xampp\htdocs\avaliacao360\app\index.php (13)
